# -*- coding: utf-8 -*-
"""M22MA002_Q7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HRnKUmmUIvKaBMaeEcg9ZZ51AoH5Jtan
"""

import numpy as np
import cv2 as cv
from google.colab.patches import cv2_imshow
import matplotlib.pyplot  as plot

img1=cv.imread("/content/11_1.png")
cv2_imshow(img1)
img2=cv.imread("/content/27_2.png")
cv2_imshow(img2)

gray_img1 = cv.cvtColor(img1,cv.COLOR_BGR2GRAY)
cv2_imshow(gray_img1)
gray_img2 = cv.cvtColor(img2,cv.COLOR_BGR2GRAY)
cv2_imshow(gray_img2)

"""FOR THE FIRST IMAGE WE NEED TO CHECK WHETHER IT HAS LIGH OR DARK BACKGROUND."""

kernel_x = np.array([[-1,0,1],
                    [-2,0,2],
                    [-1,0,1]])
kernel_y = np.array([[1, 2, 1],
                    [0, 0, 0]
                    ,[-1,-2,-1]])
grad_x = cv.Sobel(gray_img1, cv.CV_16S,1, 0, ksize=3, scale=1, delta=0 , borderType=cv.BORDER_DEFAULT)
print(grad_x)
grad_y = cv.Sobel(gray_img1, cv.CV_16S,0, 1, ksize=3, scale=1, delta=0 , borderType=cv.BORDER_DEFAULT)
print(grad_y)

cv2_imshow(grad_x)
cv2_imshow(grad_y)

h,w=grad_x.shape
w,h

for i in range(len(grad_x[h//2])):
  if grad_x[h//2][i+1]>grad_x[h//2][i]:
    print(f"img1 WHO is: Light background")
    break
  if grad_x[h//2][i+1]<grad_x[h//2][i]:
    print(f"img1 WHO is :Dark background")
    break
# grad_x[65][:]

"""FOR THE SECOND IMAGE ...WE NEED TO CHECK THE DARK BACKROUND OR LIGHT BACKGROUND"""

kernel_x = np.array([[-1,0,1],
                    [-2,0,2],
                    [-1,0,1]])
kernel_y = np.array([[1, 2, 1],
                    [0, 0, 0]
                    ,[-1,-2,-1]])
grad_x = cv.Sobel(gray_img2, cv.CV_16S,1, 0, ksize=3, scale=1, delta=0 , borderType=cv.BORDER_DEFAULT)
print(grad_x)
grad_y = cv.Sobel(gray_img2, cv.CV_16S,0, 1, ksize=3, scale=1, delta=0 , borderType=cv.BORDER_DEFAULT)
print(grad_y)

cv2_imshow(grad_x)
cv2_imshow(grad_y)

h,w=grad_x.shape
w,h

for i in range(len(grad_x[h//2])):
  if grad_x[h//2][i+1]>grad_x[h//2][i]:
    print("img2 BANK IS Light background")
    break
  if grad_x[h//2][i+1]<grad_x[h//2][i]:
    print("img2 BANK IS Dark background")
    break
# grad_x[31][:]

