# -*- coding: utf-8 -*-
"""M22MA002_Q2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1arkYtUY3w951V4Ejj8p4beACxl1j51tz
"""

!pip install easyocr

import matplotlib.pyplot as plot
import cv2
import easyocr
from pylab import rcParams
from IPython.display import Image
from PIL import Image
rcParams['figure.figsize']=8,16

img=Image.open("/content/india-map.jpg")
img

reader = easyocr.Reader(['en'])

text=reader.readtext(img)
text

print(type(text))
print(len(text))
for i in range (0,(len(text)-1)):
  if text[i][1].islower():
    del text[i]
print(text)
print(len(text))
print(" distance between two states")
cord1=text[5][1]
print(cord1)
cord2=text[10][1]
print(cord2)
print (text[0])

cord1=text[5][0]
cord2=text[10][0]
# l1,l2=text.index(['HARYANA'])print(l1)
cord1
# cord2

"""Here we will be directly picking two states and through their respective index we find the centroid of the  coordinates of the text and use euclidean and manhattan distance."""

cord2
#Distance between JAMMU AND HIMACHAL 
print()
print(cord1[0][1])
avgx1=(cord1[0][0]+cord1[1][0]+cord1[2][0]+cord1[3][0])/4
avgy1=(cord1[0][1]+cord1[1][1]+cord1[2][1]+cord1[3][1])/4
avgx2=(cord2[0][0]+cord2[1][0]+cord2[2][0]+cord2[3][0])/4
avgy2=(cord2[0][1]+cord2[1][1]+cord2[2][1]+cord2[3][1])/4

distance= ((avgx1-avgx2)**2 + (avgy1-avgy2)**2)**0.5

print(f"euclidean distance between two states is {distance}")

manhattan=abs(avgy2-avgy1)+abs(avgx2-avgx1)
print(f"manhattan distance between two states is {manhattan}")

