# -*- coding: utf-8 -*-
"""M22MA002_Q1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1N-NSM5C2L_cQei54SBU38wLT8hYpWeC_
"""

pip install image-slicer

import image_slicer as islicer
import cv2 as cv
import numpy as np
import imutils
from google.colab.patches import cv2_imshow
from PIL import Image
from PIL import ImageChops as chopper

islicer.slice('/content/Spot_the_difference.png', 2)

img1 = cv.imread("/content/Spot_the_difference_01_01.png")
img2 = cv.imread("/content/Spot_the_difference_01_02.png")
gray1 = cv.cvtColor(img1, cv.COLOR_BGR2GRAY)
gray2 = cv.cvtColor(img2, cv.COLOR_BGR2GRAY)
mismatch = cv.absdiff(gray1,gray2)
cv2_imshow(img1)
cv2_imshow(img2)
cv2_imshow(mismatch)

t_image = cv.threshold(mismatch, 0, 255, cv.THRESH_BINARY | cv.THRESH_OTSU)[1]
cv2_imshow(t_image)

filter = np.ones((4,4), np.uint8)
objects = cv.dilate(t_image, filter, iterations=3)
# cv2_imshow(objects)

find_objects = cv.findContours(objects.copy(), cv.RETR_EXTERNAL, cv.CHAIN_APPROX_SIMPLE)
all_diffs = imutils.grab_contours(find_objects)

for i in all_diffs:
  if cv.contourArea(i)>20:
    x,y,h,w = cv.boundingRect(i)
    cv.rectangle(img2, (x,y), (x+h, y+w), (0,0,255),3)
x = np.zeros((300,8,3), np.uint8)
output = np.hstack((img1, img2))
cv2_imshow(output)