# -*- coding: utf-8 -*-
"""M22MA002_Q10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NLK9EfCQWURq_JXSb8bDEB2RkIwSPgiy
"""

import numpy as np
import cv2 as cv
from google.colab.patches import cv2_imshow
# !pip install easyocr
import easyocr

img1=cv.imread("/content/Screenshot 2023-01-08 at 5.14.24 PM.png",1)
img2=cv.imread("/content/Screenshot 2023-01-08 at 5.14.47 PM.png",1)
cv2_imshow(img1)
cv2_imshow(img2)

reader = easyocr.Reader(['en'])

text=reader.readtext(img1)
print(f"1st mobile no is {text[0][1]}")
text2=reader.readtext(img2)
print(f"2nd mobile no is {text2[0][1]}")

mob1=text[0][1]
mob2=text2[0][1]

print(type(text[0][1]))

print(f"last three digits of the 1st mobile no. {mob1[(-3):]}")

print(f"last three digits of the 2nd mobile no. {mob2[(-3):]}")

