# -*- coding: utf-8 -*-
"""M22MA002_Q3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/136IQ-Z8ah6RMEI1nifgObBZjTqjda13o
"""

import numpy as np
import cv2 as cv 
from google.colab.patches import cv2_imshow

img=cv.imread("/content/circle-updated.png",0)
cv2_imshow(img)
cv.waitKey(0)
cv.destroyAllWindows()

print(img.shape)
print(img)
zero=[]
print(img[212])
for i in range(590):
  if img[212][i]==0:
    print(i)
    zero.append(i)


zero
Diameter=zero[4]-zero[1]
print(f"DIAMETER OF THE CIRCLE {Diameter}")

print(f"AREA OF THE CIRCLE{3.14*(Diameter**2)/4}")
print(f"Perimeter of the Circle{3.14*Diameter}")

