# -*- coding: utf-8 -*-
"""M22MA002_Q8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kSDu7uyIx3SBWENWjUOPUKDMGZcG75Kk
"""

import numpy as np
import cv2 as cv
from google.colab.patches import cv2_imshow
from matplotlib import pyplot as plt

img=cv.imread("/content/IMG_20230202_163336.jpg",1)
cv2_imshow(img)
# w, h = img.shape[::-1]
# print(w,h)

template=cv.imread("/content/IMG_20230202_163453.jpg",0)
w, h = template.shape[::-1]
cv2_imshow(template)
print(w,h)
template=template[150:450,90:300]
template=cv.resize(template,(120,250))
cv2_imshow(template)
w, h = template.shape[::-1]
# w0,h0=cv2_imshow(template)
img_gray = cv.cvtColor(img, cv.COLOR_BGR2GRAY)
res = cv.matchTemplate(img_gray,template,cv.TM_CCOEFF_NORMED)
min_val, max_val, min_loc, max_loc = cv.minMaxLoc(res)
threshold = 0.46265455
loc = np.where(res >= threshold)

for pt in zip(*loc[::-1]):
    cv.rectangle(img, pt, (pt[0] + w, pt[1] + h), (0, 0, 255), 2)
  
# Show the final image with the matched area.
cv2_imshow(img)

