# -*- coding: utf-8 -*-
"""M22ma002_Qqu3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/175sAI75ggj_OOQV9rEa1yWS_b-zDfkTp
"""

!pip -q install -U ultralytics
import ultralytics
ultralytics.checks()

import os
os.chdir(os.getcwd())

from google.colab import drive
drive.mount('/content/drive')

!unzip -qq /content/drive/MyDrive/Datasets.zip

!yolo train model=yolov8n.pt data="/content/Datasets/deer_dataset.yaml" epochs=100 imgsz=640 batch=5

